### ISSUE TITLE
Self-loops look strange in Network Explorer

### ISSUE THREAD

**Issue by thocevar** [biolab/orange3-network#188] opened 2021-02-01 19:04 UTC
![image](https://user-images.githubusercontent.com/919223/106505397-8acf2480-64c8-11eb-9775-8fa677629085.png)

The selected node has a self-loop (it's not two nodes in the same place or something like that). This is from example dataset `mips_c2_cp_leu`.

**Comment by ajdapretnar** [comment] 2021-02-02 07:54
I think this will be fixed in #178.

**Comment by thocevar** [comment] 2021-02-02 08:18
No, not yet. :)

**Comment by janezd** [comment] 2021-02-02 09:56
> No, not yet. :)

Should now.

**Comment by janezd** [comment] 2021-02-02 09:57
Duplicate of #174.

**Closed by janezd** 2021-02-02 09:57 UTC
