### ISSUE TITLE
[BUG] Computing Node-level indices when Network is constructed from columns

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-network#17] opened 2016-11-04 09:04 UTC
Orange version: 3.3.9. 
Orange Network: last commit 9f152727f424fec65a1838b5460122d88bd614d4 

Fails when computing Node-level indices for columns. 

1. Construct a Network from distances where distances are computed between **columns**
2. Run Network analysis, and select e.g. Node-level indices > Degree

**Comment by kernc** [comment] 2017-01-03 18:54
I guess the problem is in _Distances_ widget (or `DistMatrix`) which doesn't set `row_items` and `col_items` to transposed table. AFAIC, deferred till after pandas.

**Comment by janezd** [comment] 2018-12-19 22:08
Fixed by #101.

**Closed by janezd** 2018-12-19 22:08 UTC
