### ISSUE TITLE
Network Explorer: remaining subnetwork info doesn't get cleared

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#263] opened 2023-11-13 09:10 UTC
##### Network version

0.8

##### Orange version

3.36.0

##### Expected behavior
Remaining subnetwork info gets cleared once the datasets changes.

##### Actual behavior
The info from the previous datasets remains.

##### Steps to reproduce the behavior
Network File - Network Explorer
Start with airtraffic, change to davis.

**Comment by janezd** [comment] 2023-11-13 13:44
Sounds like a duplicate of #111?

(#111 is annoyingly difficult to fix. #184 is going nowhere.)

**Closed** 2024-02-13 11:10 UTC
