### ISSUE TITLE
Network Explorer: strangest bug in drawing

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#229] opened 2021-07-16 07:24 UTC
##### Network version

1.6.0

##### Orange version

3.30.dev

##### Expected behavior
One can normally open Network Explorer during drawing.

##### Actual behavior
Network Explorer is sent into downward spiral of strange errors upon clicking it and stalls.
It only happens with _mips_c2_cp_leu.net_. 🤷‍♀️ 

##### Steps to reproduce the behavior
Network File (_mips_c2_cp_leu.net_) - Network Explorer. When the Network Explorer is still drawing the network, try to open it.

##### Additional info (worksheets, data, screenshots, ...)
Beginning of the traceback. Afterwards there's a long stack of Python Mac errors.

```
----------------------------- TypeError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-network/orangecontrib/network/widgets/graphview.py", line 140, in paint
    sizes = self.sizes[::2][arcs] + w3[arcs]
TypeError: 'float' object is not subscriptable
-------------------------------------------------------------------------------
QLayout: Attempting to add QLayout "" to ErrorReporting "", which already has a layout
QLayout: Attempting to add QLayout "" to ErrorReporting "", which already has a layout
2021-07-16 09:12:13.218 python[2495:14578279] -[NSApplication runModalSession:] may not be invoked inside of transaction begin/commit pair, or inside of transaction commit (usually this means it was invoked inside of a view's -drawRect: method.) The modal dialog has been suppressed to avoid deadlock.
```

**Comment by ajdapretnar** [comment] 2021-07-16 11:57
Happens also on File (iris) - Louvain Clustering - Network Explorer.

**Comment by janezd** [comment] 2021-08-01 09:55
What do you mean by "during drawing"? During layout optimization? If so, this is a duplicate of #190; I'm incapable of properly implement threading. You also noticed this in #219: the optimization is supposed to run in a different thread without blocking anything, but it does not.

**Comment by ajdapretnar** [comment] 2021-08-03 08:12
But in #190 you need to change parameters? Here, you don't have to. Just open the widget while it is still in the "layout optimization" phase. But what do I know - it surely could be an issue of threading.

**Comment by janezd** [comment] 2021-08-19 18:26
You're right: this has nothing to do with threading, or opening the widget at a wrong moment. It's a simple bug that occurs when drawing unweighted networks with arcs (loops).

**Closed** 2021-08-23 07:33 UTC
